### ISSUE TITLE
Build from Official Oracle Image?

### ISSUE THREAD

**Issue by danpoltawski** [moodlehq/moodle-db-oracle#4]
I just came across this and saw that Oracle now have an 'official' image you could convert to:

https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance

**Comment by andrewnicols** [comment]
Thanks Dan,

Is that a new image or the one which you have to be logged in to get?

I know they were talking about doing it properly so I’ve been hanging out for it.

Thanks for the heads up :)

**Comment by andrewnicols** [comment]
New image.

Nothing in their FAQ about uploading to dockerhub. The binaries are not included, you have to add them, so making a public image may still contravene their license.

Still, we should still switch and we can deal with that somehow, either a private image for hq and/or a requirement to put the binary zip in a mounted volume. Will have a look more soon.

**Comment by aspark21** [comment]
Noting this might be worth revisiting moodlehq/moodle-php-apache/pull/148

https://hub.docker.com/r/gvenzl/oracle-xe seems like a well maintained base image to switch too
Made a quick draft of the change here - https://github.com/moodlehq/moodle-db-oracle/compare/master...aspark21:patch-1

Probably won't have time to look at this in more depth until after Easter as likely to be quite a bit of dependencies to test for this.

**Comment by stronk7** [comment]
Hi @aspark21,

just was reviewing open issues when saw your comment above. Note that we are already using that image as base for the 21c tag of the images ([available since few hours ago](https://hub.docker.com/r/moodlehq/moodle-db-oracle-r2)).

Regarding using Oracle images... yes, we can build from that repository... and, since recently, we can also use their images, available in their own containers registry @ https://container-registry.oracle.com/ . But in both cases we have to login and accept some stuff (haven't looked to the details).

It's good that Oracle is progressively opening their hands, first with the scripts, later with the registry... let's see if they make them freely available for developing and testing purposes.

In the mean time... I'm going to close this now, so far we are covered with current sources and I hope they won't be abruptly removed again by Oracle/Docker.

Ciao :-)
